language: node_js
os:
  - windows
node_js:
  - "11"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install jdk8; "C:/ProgramData/chocolatey/bin/RefreshEnv.cmd"; fi
script:
  - npm t
